name: "Markdown checks"

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: articulate/actions-markdownlint@v1
        with:
          files: 'docs/**/*.md'
          version: 0.28.1
